import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Load OvenLiveKit UMD so window.OvenLiveKit is available */}
        <Script
          src="https://cdn.jsdelivr.net/npm/ovenlivekit@1.4.0/dist/OvenLiveKit.min.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className={inter.className}>
        <div className="app-container">
          <main className="main-content">{children}</main>
        </div>
      </body>
    </html>
  );
}
